"""Add tenants

Revision ID: 19ca565aef45
Revises: 36e812d3a8b9
Create Date: 2026-06-08 19:35:20.448441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ca565aef45'
down_revision = '36e812d3a8b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('allowed_domain', sa.String(length=200), nullable=True),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.Column('logo_data', sa.LargeBinary(), nullable=True),
    sa.Column('logo_mimetype', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tenant_id')

    op.drop_table('tenants')
    # ### end Alembic commands ###
